=pod

=head1 NAME

PlatypusMan - Template based S5 Generation

=head1 VERSION

version 0.01

=head1 BUNDLED FILES

=head2 s5

=head2 sh

=head2 themes

=head1 METHODS

=head2 Platypus::Man->share_dir

Returns the share directory for this dist in the form
of a L<Path::Class::Dir> object.

=head1 AUTHOR

Graham Ollis <perl@wdlabs.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2013 by Graham Ollis.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

